apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  password: NTExNjNtYWhtb3VkbG92ZXNtYXJtb3Jh
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-sc
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
